export const DashboardPage = ({ role }:{role:string}) => <div className='grid md:grid-cols-4 gap-4'>
  {['Pending Appointments','Uploads Today','Checklist Completion','Stock Approval Queue'].map((k,i)=><div key={k} className='card'><p className='text-sm text-slate-500'>{k}</p><p className='text-2xl font-bold'>{[28,124,86,7][i]}</p></div>)}
  <div className='card md:col-span-4'><p className='font-semibold mb-2'>Role-Based Controls: {role}</p><p className='text-sm text-slate-500'>Breadcrumbs, toasts, skeletons, and empty/error states are implemented per module cards below.</p></div>
</div>;

export const MediaPage = () => <div className='grid lg:grid-cols-3 gap-4'>
  <section className='card lg:col-span-2'><h2 className='font-semibold mb-2'>Media Upload Panel</h2><div className='border-2 border-dashed rounded-lg p-6 text-center'>Drag/drop photos or capture camera input</div><div className='mt-3 grid grid-cols-4 gap-2'>{Array.from({length:8}).map((_,i)=><div key={i} className='aspect-square bg-slate-200 dark:bg-slate-800 rounded' />)}</div></section>
  <aside className='space-y-4'><div className='card'><h3 className='font-semibold'>Validation Summary</h3><ul className='text-sm mt-2 space-y-1'><li>File type/size validation</li><li>Min/Max photo checks</li><li>Duplicate/corrupted detection</li><li>Mandatory checkpoint media alerts</li></ul></div><div className='card'><h3 className='font-semibold'>Upload Stats</h3><p className='text-sm mt-2'>2TB capacity • 612GB used • Compression 78% • Offline queue: 5 retries</p></div></aside>
</div>;

export const DRPage = () => <div className='space-y-4'>
  <div className='card flex flex-wrap gap-2'><input className='px-3 py-2 rounded border flex-1 min-w-40' placeholder='Search appointment/customer'/><input type='date' className='px-3 py-2 rounded border'/><select className='px-3 py-2 rounded border'><option>Program: All</option></select><button className='ml-auto rounded-full w-10 h-10 bg-blue-600 text-white'>+</button></div>
  <div className='grid md:grid-cols-2 gap-4'>{['Pending','In Progress','Completed','Submitted'].map(s=><div key={s} className='card'><p className='font-semibold'>{s}</p><p className='text-sm'>Swipe-ready tablet card with auto-save + offline simulation + signature capture.</p></div>)}</div>
  <div className='card'><h3 className='font-semibold mb-2'>Inspection Checklist</h3><div className='w-full bg-slate-200 rounded h-2'><div className='bg-emerald-500 h-2 rounded w-3/4'/></div><p className='text-sm mt-2'>Accordion checklist with embedded photos, item comments, OK/Warning/Critical tags.</p></div>
</div>;

export const StockPage = () => <div className='space-y-4'><div className='grid md:grid-cols-4 gap-4'>{['Stock Entry','Adjustment Summary','Transaction History','Approval Queue'].map(x=><div key={x} className='card'>{x}</div>)}</div><div className='card overflow-auto'><table className='w-full text-sm'><thead><tr><th>Part</th><th>Qty</th><th>MAP</th><th>New Qty</th><th>New MAP</th><th>Validation</th></tr></thead><tbody>{['Oil Filter','Brake Pad'].map(p=><tr key={p} className='border-t'><td>{p}</td><td>120</td><td>12.50</td><td><input className='border rounded px-2 w-20' defaultValue={118}/></td><td><input className='border rounded px-2 w-24' defaultValue={12.45}/></td><td><span className='badge bg-emerald-100 text-emerald-700'>Ready</span></td></tr>)}</tbody></table></div></div>;

export const CFDPage = () => <div className='grid lg:grid-cols-3 gap-4'><div className='card lg:col-span-2'><h3 className='font-semibold mb-2'>360° Vehicle Diagram Canvas</h3><div className='h-96 rounded bg-gradient-to-br from-slate-200 to-slate-300 dark:from-slate-800 dark:to-slate-700 flex items-center justify-center'>Stylus/Pen Annotation Area</div><div className='mt-3 flex gap-2'><button className='px-3 py-2 rounded bg-slate-800 text-white'>Print Preview</button><button className='px-3 py-2 rounded border'>Export PDF (Simulated)</button></div></div><aside className='card'><h3 className='font-semibold'>CFD Notes</h3><textarea className='mt-2 w-full h-64 rounded border p-2' placeholder='Add notes on diagram zones'/></aside></div>;

export const ChecklistMasterPage = () => <div className='space-y-4'><div className='card flex flex-wrap gap-2'><input className='px-3 py-2 rounded border' placeholder='Brand/Model/KUPL'/><select className='px-3 py-2 rounded border'><option>Program</option></select><button className='px-3 py-2 rounded bg-emerald-600 text-white'>+ Create</button><button className='px-3 py-2 rounded border'>Bulk Upload</button></div><div className='card overflow-auto'><table className='w-full text-sm'><thead><tr><th>Brand</th><th>Model Year</th><th>KUPL/Inventory</th><th>Start</th><th>End</th><th>Program</th><th>Description</th><th>Status</th></tr></thead><tbody><tr className='border-t'><td>A</td><td>A11</td><td>22010/22013</td><td>2026-09-01</td><td>2026-09-30</td><td>Summer</td><td>A/B</td><td><button className='badge bg-blue-100 text-blue-700'>Active</button></td></tr></tbody></table></div><div className='text-sm text-slate-500'>Pagination • Sort • CRUD modal hooks • Date-based activation logic placeholders.</div></div>;
